version: '3.3'

networks:
  commons-api:
    driver: bridge

volumes:
  elasticsearch_data:
    driver: local

services:
  postgres-compose:
    image: postgres
    restart: always
    container_name: postgres-compose
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"

    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - commons-api
  app-compose:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: app-ldb
    environment:
      - PROFILE=local
      - DB_URL=jdbc:postgresql://postgres-compose:5432/postgres?currentSchema=public
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8081:8081"
    networks:
      - commons-api
    depends_on:
      - postgres-compose